// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQN-no1NdC_xj0vy_RPWD0SvuwdRWLq1U',
    appId: '1:498494703499:web:5fb7f99879077664b4518e',
    messagingSenderId: '498494703499',
    projectId: 'exp-fifth',
    authDomain: 'exp-fifth.firebaseapp.com',
    storageBucket: 'exp-fifth.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4TsbE2HEXtBywYjupZGMv_e_3zvj65EE',
    appId: '1:498494703499:android:98c6fa94d880b9bdb4518e',
    messagingSenderId: '498494703499',
    projectId: 'exp-fifth',
    storageBucket: 'exp-fifth.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgbAs7j32KF3yGjG2D4QEn0MGlFBtBpm4',
    appId: '1:498494703499:ios:6202180d388bd671b4518e',
    messagingSenderId: '498494703499',
    projectId: 'exp-fifth',
    storageBucket: 'exp-fifth.appspot.com',
    iosClientId: '498494703499-klsu62hv7bs2c9a8qed9s54rl8k34gho.apps.googleusercontent.com',
    iosBundleId: 'com.example.exp05',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgbAs7j32KF3yGjG2D4QEn0MGlFBtBpm4',
    appId: '1:498494703499:ios:6202180d388bd671b4518e',
    messagingSenderId: '498494703499',
    projectId: 'exp-fifth',
    storageBucket: 'exp-fifth.appspot.com',
    iosClientId: '498494703499-klsu62hv7bs2c9a8qed9s54rl8k34gho.apps.googleusercontent.com',
    iosBundleId: 'com.example.exp05',
  );
}
